### PR TITLE
Add CI on openjdk14. Update contributor info.

### PR DESCRIPTION
**Pull request by NingZhang-e**
1. More CI for openjdk14
2. Update contributor info.
3. Adapt to Github actions.
4. Remove Travis configuration.

### CODE REVIEW

**Comment by NingZhang-e** [comment]
@johanhaleby Please have one look. 
The build is fine on my fork: https://github.com/NingZhang-e/aspectj-maven-plugin/actions
Since Travis requires credit change now, see https://travis-ci.com/github/johanhaleby/aspectj-maven-plugin/requests
I am trying to switching to Github actions.

**Comment by johanhaleby** [comment]
Great stuff @NingZhang-e ! Would you like to be a contributor to the project? I can give you access so you don't need to supply PR's if you like.

**Comment by NingZhang-e** [comment]
> Great stuff @NingZhang-e ! Would you like to be a contributor to the project? I can give you access so you don't need to supply PR's if you like.

Sure, please.

Also need your help if new deployment to Maven Central is required.

**Comment by johanhaleby** [comment]
No problem, just ping me and I'll make a new maven central release. Maybe we could do it even nicer with a github action of some sort? Not sure if it's worth the effort though since it's not that often we need to make a new release I suppose?

I've sent you an invite now.

**Comment by NingZhang-e** [comment]
> No problem, just ping me and I'll make a new maven central release. Maybe we could do it even nicer with a github action of some sort? Not sure if it's worth the effort though since it's not that often we need to make a new release I suppose?
> 
> I've sent you an invite now.

Yes, I have accepted the invitation.

I will investigate if Github actions could help deploy to Maven central. (This seems can not be achieved completely automatically since need manual check after deployed to Sonatype). But it worth trying!

**Pull request merged**
